import { readKit } from "../bin/kit";
import type { CdragonBin } from "../raw/cdragon";
import type { DdragonChampionFull } from "../raw/ddragon";
import { auditSpell, type Resolution } from "./placeholders";

const RESOLUTIONS: Resolution[] = [
  "ui-hook",
  "ddragon-effect",
  "ddragon-vars",
  "ddragon-datavalues",
  "cdragon-calculation",
  "cdragon-datavalue",
  "cdragon-effectamount",
  "unresolved",
];

const SLOTS = ["Q", "W", "E", "R"] as const;

function tally(resolutions: Resolution[]): Record<Resolution, number> {
  const counts = Object.fromEntries(RESOLUTIONS.map((r) => [r, 0])) as Record<Resolution, number>;
  for (const r of resolutions) counts[r]++;
  return counts;
}

const pct = (n: number, d: number) => (d === 0 ? "—" : `${((100 * n) / d).toFixed(1)}%`);

/**
 * Markdown report of where tooltip placeholders can be resolved from. Deterministic for fixed
 * inputs (no timestamps), so it can be committed and diffed.
 */
export function placeholderAuditReport(
  full: DdragonChampionFull,
  bins: Record<string, CdragonBin>,
): string {
  const lines: string[] = [];
  const champions = Object.values(full.data).sort((a, b) => a.id.localeCompare(b.id));

  // Site-wide: what ddragon alone can resolve.
  const all = champions.flatMap((c) => c.spells.flatMap((s) => auditSpell(s)));
  const counts = tally(all.map((p) => p.resolution));
  const valueBearing = all.length - counts["ui-hook"];
  const ddragonResolved =
    counts["ddragon-effect"] + counts["ddragon-vars"] + counts["ddragon-datavalues"];
  lines.push(
    `# Placeholder audit — ddragon ${full.version}`,
    "",
    "Generated by `pnpm etl audit`. Do not edit by hand.",
    "",
    `## All champions (${champions.length}), ddragon only`,
    "",
    "| Resolution | Placeholders |",
    "|---|---|",
    ...RESOLUTIONS.filter((r) => !r.startsWith("cdragon")).map((r) => `| ${r} | ${counts[r]} |`),
    `| **total** | ${all.length} |`,
    "",
    `Value-bearing placeholders (excluding UI hooks): ${valueBearing}; resolvable from ddragon: ` +
      `${ddragonResolved} (${pct(ddragonResolved, valueBearing)}).`,
    "",
    "Cross-spell placeholders (`spell.<name>:<var>`): " +
      `${all.filter((p) => p.spell !== undefined).length}.`,
    "",
    "Expression placeholders (e.g. `slowamount*100`): " +
      `${all.filter((p) => p.multiplier !== undefined).length}.`,
    "",
  );

  // Probe champions: ddragon + CDragon bin.
  lines.push("## Probe champions, ddragon + CDragon bin", "");
  for (const [id, bin] of Object.entries(bins).sort(([a], [b]) => a.localeCompare(b))) {
    const champion = full.data[id];
    if (!champion) throw new Error(`${id} not in championFull ${full.version}`);
    const kit = readKit(bin);
    const perSpell = SLOTS.map((slot, i) => {
      const spell = champion.spells[i];
      if (!spell) throw new Error(`${id} has no ${slot} spell`);
      return {
        slot,
        spell,
        audit: auditSpell(spell, { bin, ability: kit.abilities.find((a) => a.slot === slot) }),
      };
    });
    const c = tally(perSpell.flatMap((s) => s.audit.map((p) => p.resolution)));
    const value = perSpell.reduce((n, s) => n + s.audit.length, 0) - c["ui-hook"];
    const fromBin = c["cdragon-calculation"] + c["cdragon-datavalue"] + c["cdragon-effectamount"];
    lines.push(
      `### ${champion.name} (\`${id}\`)`,
      "",
      `Value-bearing placeholders: ${value} · ddragon: ${c["ddragon-effect"] + c["ddragon-vars"] + c["ddragon-datavalues"]}` +
        ` · CDragon bin: ${fromBin} · unresolved: ${c.unresolved} · bin coverage ${pct(fromBin, value)}`,
      "",
      "| Slot | Spell | Placeholder | Resolution |",
      "|---|---|---|---|",
    );
    for (const { slot, spell, audit } of perSpell) {
      for (const p of audit.filter((p) => p.resolution !== "ui-hook")) {
        lines.push(`| ${slot} | ${spell.id} | \`${p.raw}\` | ${p.resolution} |`);
      }
    }
    if (kit.warnings.length) lines.push("", ...kit.warnings.map((w) => `- ⚠ ${w}`));
    const missing = kit.abilities.flatMap((a) => a.missing.map((m) => `${a.slot}: ${m}`));
    if (missing.length) lines.push("", `Child spells not in bin: ${missing.join(", ")}`);
    lines.push("");
  }
  return lines.join("\n");
}
